config/routes.rb
Rails.application.routes.draw do

  # Static stuff
  root 'static#index'
  get 'faq' => 'static#faq'
  get 'imprint' => 'static#contactimprint'

  # Controllers
  get 'projects/public'
  resources :projects do
    scope :helpers do
      get 'confirm/:confirmation_key' => 'helpers#confirm', as: :helpers_confirm
      get 'unsubscribe' => 'helpers#unsubscribe', as: :helpers_unsubscribe
      get 'subscribe_many' => 'helpers#subscribe_many', as: :helpers_subscribe_many
      post 'subscribe_many' => 'helpers#subscribe_many_post', as: :helpers_subscribe_many_post
      get 'unsubscribe_many' => 'helpers#unsubscribe_many', as: :helpers_unsubscribe_many
      post 'unsubscribe_many' => 'helpers#unsubscribe_many_post', as: :helpers_unsubscribe_many_post
    end
    resources :helpers
    resources :managers

    resources :requests do
      get 'accept'
      get 'decline'
    end
  end

  if ENV['ENABLE_ADMIN'] == "TRUE"
    # Sidekiq
    require 'sidekiq/web'
    mount Sidekiq::Web => '/admin/sidekiq'
    # Admin
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end

  devise_for :managers, controllers: {
                 confirmations: 'managers/confirmations',
                 sessions: 'managers/sessions'
               }

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :project
  belongs_to :manager_in_charge, foreign_key: :manager_in_charge_id, class_name: :Manager
  has_many :request_statuses
  has_and_belongs_to_many :helpers, join_table: :request_statuses

  TIMEOUT_DIVIDER = 10.0
  MINIMUM_TIMEOUT = 5

  rails_admin do
    list do
      field :project
      field :name
      field :state
      field :description
      field :amount
      field :end
      field :manager_in_charge
    end
  end

  def timeout_time
    total_runtime = ((self.end - self.start).to_i / 60)
    timeout = (total_runtime / TIMEOUT_DIVIDER).to_i
    [timeout, MINIMUM_TIMEOUT].max
  end

  def last_deadline_from t
    t - timeout_time
  end

  def next_deadline_from t
    t + timeout_time
  end

  def confirmed_helpers
    self.helpers.where {request_statuses.accepted == true}
  end

  def pending_helpers
    self.helpers.where {(request_statuses.accepted == nil) & (request_statuses.timeout == false)}
  end

  def next_helpers
    Helper.where { (id << my{self.helpers}) & (validated == true) }.order('random()')
  end

  # State machine
  include AASM
  aasm :column => :state do
    # A request is in the `pending` state until the `start` time
    state :pending, initial: true
    # A request is in the `searching_helpers` state as long as there
    # are not enough helpers found and the time is < `end` time
    state :searching_helpers
    # A request finished successful when enough helpers where found in
    # the given time frame
    state :success
    # A request failed when there were not enough helper that
    # responded positively
    state :failed, before_enter: :timeout_helpers!

    event :start_searching do
      transitions from: :pending, to: :searching_helpers
    end
    event :successfully_found do
      transitions from: :searching_helpers, to: :success
    end
    event :failed_to_find do
      transitions from: :searching_helpers, to: :failed
    end
    event :cancel do
      transitions from: [:pending, :searching_helpers], to: :failed
    end
  end

  private

  def timeout_helpers!
    ActiveRecord::Base.transaction do
      request_statuses.each do |status|
        status.timeout = true
        status.save
      end
    end
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_project, except: [:accept, :decline]
  before_action :set_request, only: [:show, :edit, :update, :destroy, :accept, :decline]
  authorize_resource

  def index
    @requests = @project.requests
    @requests = @requests.order(created_at: :desc)
    @title = I18n.t "request.manage_requests"
  end

  # GET /requests/1
  def show
    @title = @request.name
  end

  # GET /requests/new
  def new
    @request = Request.new project: current_manager.project, manager_in_charge: current_manager
    @request.start = Time.now
    @request.end = @request.start.change({hour: 18, min: 0, sec: 0})
    if @request.end < @request.start
      @request.end += 1.day
    end
    @title = I18n.t "request.create"
    render '_form'
  end

  # GET /requests/1/edit
  def edit
    @title = @request.name
    render '_form'
  end

  # POST /requests
  def create
    @request = @project.requests.new(request_params)
    if @request.save
      Rails.logger.info("Request created")
      RequestWorker.perform_at(@request.start, @request.id)
      redirect_to project_request_path(@project, @request), notice: I18n.t("request.created_successfully")
    else
      @title = I18n.t "request.create"
      render '_form'
    end
  end

  # PATCH/PUT /requests/1
  def update
    if @request.update(request_params)
      redirect_to project_requests_path(@project, @request), notice: I18n.t("request.updated_successfully")
    else
      @title = @request.name
      render '_form'
    end
  end

  def accept
    @title = @request.name
    if request_status_ok?
      @request_status.accept
      Rails.logger.info("Request accepted")
      RequestWorker.perform_async(@request.id)
    end
  end

  def decline
    @title = @request.name
    if request_status_ok?
      @request_status.decline
      Rails.logger.info("Request declined")
      RequestWorker.perform_async(@request.id)
    end
  end

  private
  def set_project
    @project = Project.friendly.find(params[:project_id])
    raise ActiveRecord::RecordNotFound if @project.nil?
  end

  def set_request
    id = params[:id] || params[:request_id]
    if @project
      @request = @project.requests.find(id)
    else
      @request = Request.find(id)
    end
    raise ActiveRecord::RecordNotFound if @request.nil?
  end

  def request_status_ok?
    @request_status = @request.request_statuses.joins(:helper).where { helpers.email == my{params[:email]} }.first
    raise ActiveRecord::RecordNotFound if @request_status.nil?
    if @request_status.timeout?
      render "timeout"
      return false
    end
    unless @request_status.accepted.nil?
      render "already_selected"
      return false
    end
    @request = @request_status.request
    return true
  end

  # Only allow a trusted parameter "white list" through.
  def request_params
    params.require(:request).permit(:name, :description, :amount, :start, :end, :timeout, :range, :project_id, :manager_in_charge_id)
  end
end

app/views/requests/_form.html.erb
<%= simple_form_for [@project,@request], html: { class: 'sky-form' } do |f| %>
<div class="row">
  <fieldset>
    <%= f.input :name, wrapper: :bootstrap %>
    <%= f.input :description %>
    <%= f.input :description_after_accept %>
    <%= f.input :amount %>

    <%= f.input :start,
                :as => :datetimepicker,
                :input_html => { :value => localize(f.object.start) } %>
    <%= f.input :end,
                :as => :datetimepicker,
                :input_html => { :value => localize(f.object.end) } %>
    <%= f.input :manager_in_charge_id, as: :select, collection: @project.managers, label_method: :email, include_blank: nil %>
  </fieldset>

  <footer>
    <%= f.submit %>
  </footer>
</div>
<% end %>

app/views/requests/_table.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>State</th>
      <th>Number of helpers</th>
      <th>Start</th>
      <th>End</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
        <td><%= request.name %></td>
        <td><%= request.state %></td>
        <td><%= request.confirmed_helpers.count %> / <%= request.amount %></td>
        <td><%= request.start %></td>
        <td><%= request.end %></td>
        <td>
          <%= link_to fa_icon('eye', text: 'Show'), project_request_path(@project, request),
          class: "btn btn-info btn-xs" %>
          <%= link_to fa_icon('pencil', text: 'Edit'), edit_project_request_path(@project, request),
          class: "btn btn-warning btn-xs" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/requests/accept.html.erb
<h2><%= I18n.t "request.thanks_for_helping", project: @request.project.name %></h2>


<h3><%= @request.name %></h3>

<p><%= @request.description %></p>
<p><%= @request.description_after_accept %></p>

app/views/requests/already_selected.html.erb
<h2>You have already selected an option</h2>
<p>Please stick to it:</p>
<% if @request_status.accepted %>
  You accepted to help
<% else %>
  You declined to help
<% end %>

app/views/requests/decline.html.erb
<h2><%= I18n.t "request.thanks_for_not_helping" %></h2>

<p><%= I18n.t "request.thanks_for_not_helping_text" %></p>

app/views/requests/index.html.erb
<%= render "table" %>

<%= link_to I18n.t("request.create"), new_project_request_path(@project), class: "btn btn-u pull-right" %>

app/views/requests/show.html.erb
<p>
  <strong>Description:</strong>
  <%= @request.description %>
</p>


<p>
  <strong>Amount:</strong>
  <%= @request.amount %>
</p>

<p>
  <strong>Start:</strong>
  <%= localize(@request.start) %>
</p>

<p>
  <strong>End:</strong>
  <%= localize(@request.end) %>
</p>

<h2>Helpers</h2>
<ul>
  <% @request.confirmed_helpers.each do |helper| %>
    <li><%= helper.contact_address %></li>
  <% end %>
</ul>