config/routes.rb
Rails.application.routes.draw do

  # Static stuff
  root 'static#index'
  get 'faq' => 'static#faq'
  get 'imprint' => 'static#contactimprint'

  # Controllers
  get 'projects/public'
  resources :projects do
    scope :helpers do
      get 'confirm/:confirmation_key' => 'helpers#confirm', as: :helpers_confirm
      get 'unsubscribe' => 'helpers#unsubscribe', as: :helpers_unsubscribe
      get 'subscribe_many' => 'helpers#subscribe_many', as: :helpers_subscribe_many
      post 'subscribe_many' => 'helpers#subscribe_many_post', as: :helpers_subscribe_many_post
      get 'unsubscribe_many' => 'helpers#unsubscribe_many', as: :helpers_unsubscribe_many
      post 'unsubscribe_many' => 'helpers#unsubscribe_many_post', as: :helpers_unsubscribe_many_post
    end
    resources :helpers
    resources :managers

    resources :requests do
      get 'accept'
      get 'decline'
    end
  end

  if ENV['ENABLE_ADMIN'] == "TRUE"
    # Sidekiq
    require 'sidekiq/web'
    mount Sidekiq::Web => '/admin/sidekiq'
    # Admin
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end

  devise_for :managers, controllers: {
                 confirmations: 'managers/confirmations',
                 sessions: 'managers/sessions'
               }

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :managers
  has_many :requests
  has_many :helpers
  before_validation do
    generate_invite_key
    slugify
  end
  include FriendlyId
  friendly_id :slug

  def admins
    managers.where { is_admin == true }
  end

  def generate_invite_key
    if self.invite_key.nil?
      self.invite_key = SecureRandom.urlsafe_base64
    end
  end

  private

  def slugify
    if self.slug.nil?
      # Suggested by http://stackoverflow.com/questions/136793/is-there-a-do-while-loop-in-ruby
      loop do
        self.slug = "#{self.name.parameterize}-#{rand(10000)}"
        break if Project.find_by_slug(self.slug).nil?
      end
     end
  end
end

app/controllers/projects_controller.rb
# coding: utf-8
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update]
  authorize_resource

  # GET /projects
  def public
    @projects = Project.where is_public: true
    @title = I18n.t "project.all_title"
  end

  # GET /projects/1
  def show
    @project = Project.friendly.find params[:id]
    @title = I18n.t "project.manage", project: @project.name
  end


  # GET /projects/new
  def new
    @manager = Manager.new
    @manager.project = Project.new
    @manager.project.is_public = true
    @title = I18n.t "project.new_title"
  end

  # GET /projects/1/edit
  def edit
    @title = I18n.t "project.edit"
    render "_form"
  end

  # POST /projects
  def create
    @title = I18n.t "project.new_title"
    @manager = Manager.new params[:project][:manager].permit(:email, :password, :password_confirmation)
    @manager.project = Project.new(project_params)
    if @manager.save
      redirect_to root_path, flash: {success:  I18n.t("project.created")}
    else
      @manager.project.validate
      render :new
    end
  end

  # PATCH/PUT /projects/1
  def update
    @title = @project.name
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render "_form"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.friendly.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def project_params
      params.require(:project).permit(:name, :is_public, :description)
    end
end

app/views/projects/_form.html.erb
<%= simple_form_for(@project, html: {class: "reg-page"}) do |f| %>

<% @manager.errors.full_messages.each do |msg| %>
  <p><%= msg %></p>
<% end unless @manager.nil? or @manager.errors.empty?%>
<% @project.errors.full_messages.each do |msg| %>
  <p><%= msg %></p>
<% end%>
<%= f.error_notification %>

<div class="row">
  <div class="reg-header">
    <h2><%= I18n.t 'project.register_title' %></h2>
  </div>
  <%= f.input :charity, as: :select, include_blank: nil, selected: false%>
  <%= f.input :name, wrapper: :no_label do %>
    <span class="input-group-addon"><i class="fa fa-user"></i></span>
    <%= f.input_field :name, class: 'form-control', placeholder: I18n.t("project.name") %>
  <% end %>

  <%= f.simple_fields_for @manager do |b| %>

    <%= b.input :email, wrapper: :no_label do %>
      <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
      <%= b.input_field :email, class: 'form-control' %>
    <% end %>
    <%= b.input :password, wrapper: :no_label do %>
      <span class="input-group-addon"><i class="fa fa-key"></i></span>
      <%= b.input_field :password, class: 'form-control' %>
    <% end %>
    <%= b.input :password_confirmation, wrapper: :no_label do %>
      <span class="input-group-addon"><i class="fa fa-key"></i></span>
      <%= b.input_field :password_confirmation, class: 'form-control' %>
    <% end %>
  <% end %>
  <div class="row">
    <div class="col-md-12">
      <%= link_to I18n.t("project.have_already_account"), new_manager_session_path %>
      <%= f.button :submit, class: 'btn-u pull-right' %>
    </div>
  </div>
</div><!--/row-->
<% end %>

app/views/projects/charities.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= link_to fa_icon("heart", text: I18n.t("project.subscribe")), new_project_helper_path(project, invite_key: project.invite_key), class: "btn btn-u" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/new.html.erb
<div class="row">
  <div class="col-md-6">
    <%= simple_form_for(@manager.project, html: {class: "reg-page"}) do |f| %>
      <div class="row">
        <!-- <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3"> -->
        <div class="reg-header">
          <h2><%= I18n.t 'project.register_title' %></h2>
        </div>
        <%= f.input :is_public, as: :select, include_blank: nil, selected: true%>
        <%= f.input :name, wrapper: :no_label do %>
          <span class="input-group-addon"><i class="fa fa-user"></i></span>
          <%= f.input_field :name, class: 'form-control', placeholder: I18n.t("project.name") %>
        <% end %>

        <%= f.simple_fields_for @manager do |b| %>
          <%= b.input :email, wrapper: :no_label do %>
            <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
            <%= b.input_field :email, class: 'form-control' %>
          <% end %>
          <%= b.input :password, wrapper: :no_label do %>
            <span class="input-group-addon"><i class="fa fa-key"></i></span>
            <%= b.input_field :password, class: 'form-control' %>
          <% end %>
          <%= b.input :password_confirmation, wrapper: :no_label do %>
            <span class="input-group-addon"><i class="fa fa-key"></i></span>
            <%= b.input_field :password_confirmation, class: 'form-control' %>
          <% end %>
        <% end %>
        <div class="row">
          <div class="col-md-12">
            <%= link_to I18n.t("project.have_already_account"), new_manager_session_path %>
            <%= f.button :submit, class: 'btn-u pull-right' %>
          </div>
        </div>
        <!-- </div> -->
      </div><!--/row-->
    <% end %>

  </div>
  <div class="col-md-6">
    <h2><%= I18n.t "project.register_advantages" %></h2>
    <ul class="list-unstyled">
      <%= t "project.register_advantages_html" %>
    </ul>
  </div>
</div>

app/views/projects/public.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= link_to fa_icon("heart", text: I18n.t("project.subscribe")), new_project_helper_path(project, invite_key: project.invite_key), class: "btn btn-u" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/show.html.erb
<h2>
  <%= I18n.t "project.description" %>
  <% if can? :edit, @project %>
    <small>
      <%= link_to I18n.t("project.edit"), edit_project_path(@project) %>
    </small>
  <% end %>
</h2>
<p><%= @project.description%></p>
<h2><%= I18n.t "project.num_of_managers", count: @project.managers.count %></h2>
<% if can? :create, @project.managers.first %>
  <%= link_to fa_icon("user-plus", text: I18n.t("project.add_manager")), new_project_manager_path(@project), class: "btn-u" %>
<% end %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= I18n.t "email" %></th>
      <th><%= I18n.t "actions" %></th>
    </tr>
  </thead>
  <tbody>
    <% @project.managers.order(is_admin: :desc).each do |manager| %>
      <tr>
        <td>
          <%= manager.display_name%>
          <%  if manager.is_admin %>
            <strong class="cred">(<%= I18n.t("manager.is_admin")%>)</strong>
          <% end %>
        </td>

        <td>
          <%= link_to fa_icon('eye', text: 'Show'), project_manager_path(@project, manager),
          class: "btn btn-info btn-xs" %>
          <% if can? :edit, manager %>
            <%= link_to fa_icon('pencil', text: 'Edit'), edit_project_manager_path(@project, manager),
            class: "btn btn-warning btn-xs" %>
            <% end %>
          <% if can? :delete, manager %>
            <%= link_to fa_icon('trash', text: 'Delete'), project_manager_path(@project, manager),
            class: "btn btn-danger btn-xs",
            method: :delete%>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<h2><%= I18n.t "project.num_of_helpers", count: @project.helpers.count %></h2>
<%= link_to fa_icon("user-plus", text: I18n.t("project.helper_subscribe")), project_helpers_subscribe_many_path(@project), class: "btn-u" %>
<%= link_to fa_icon("ban", text: I18n.t("project.helper_unsubscribe")), project_helpers_unsubscribe_many_path(@project), class: "btn-u" %>
<% if can? :show, @project.helpers.first %>
  <table  class="table table-striped">
    <thead>
      <tr>
        <th><%= I18n.t "email" %></th>
        <th><%= I18n.t "project.requests_accepted" %></th>
      </tr>
    </thead>
    <tbody>
      <% @project.helpers.each do |helper| %>
        <tr>
          <td><%= helper.contact_address %></td>
          <td><%= helper.accepted_requests.count %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>