config/routes.rb
Rails.application.routes.draw do

  # Static stuff
  root 'static#index'
  get 'faq' => 'static#faq'
  get 'imprint' => 'static#contactimprint'

  # Controllers
  get 'projects/public'
  resources :projects do
    scope :helpers do
      get 'confirm/:confirmation_key' => 'helpers#confirm', as: :helpers_confirm
      get 'unsubscribe' => 'helpers#unsubscribe', as: :helpers_unsubscribe
      get 'subscribe_many' => 'helpers#subscribe_many', as: :helpers_subscribe_many
      post 'subscribe_many' => 'helpers#subscribe_many_post', as: :helpers_subscribe_many_post
      get 'unsubscribe_many' => 'helpers#unsubscribe_many', as: :helpers_unsubscribe_many
      post 'unsubscribe_many' => 'helpers#unsubscribe_many_post', as: :helpers_unsubscribe_many_post
    end
    resources :helpers
    resources :managers

    resources :requests do
      get 'accept'
      get 'decline'
    end
  end

  if ENV['ENABLE_ADMIN'] == "TRUE"
    # Sidekiq
    require 'sidekiq/web'
    mount Sidekiq::Web => '/admin/sidekiq'
    # Admin
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end

  devise_for :managers, controllers: {
                 confirmations: 'managers/confirmations',
                 sessions: 'managers/sessions'
               }

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/helpers_controller.rb
class HelpersController < ApplicationController
  authorize_resource
  before_filter :get_project
  require 'securerandom'

  def new
    raise CanCan::AccessDenied unless params[:invite_key] == @project.invite_key
    @helper = Helper.new
    @title = I18n.t("project.subscribe_to", project: @project.name)
  end

  def create
    raise CanCan::AccessDenied unless params[:invite_key] == @project.invite_key
    @helper = Helper.new params[:helper].permit(:email)
    @helper.project = @project
    if @helper.save
      HelperMailer.optin_mail(@helper).deliver_later
      redirect_to root_path, flash:{success: I18n.t("helpers.join_success")}
    else
      @title = I18n.t("project.subscribe_to", project: @project.name)
      render "new"
    end
  end

  def confirm
    @helper = Helper.find_by_confirmation_key params[:confirmation_key]
    unless @helper.nil?
      @helper.validated = true
      @helper.save
      Rails.logger.info("Subscription")
      redirect_to root_path, flash:{success: I18n.t("helpers.confirmed")}
    else
      redirect_to root_path, flash:{danger: I18n.t("helpers.no_confirmation")}
    end
  end

  def subscribe_many
    @title = I18n.t "helpers.subscribe_many"
  end

  def subscribe_many_post
    @sent_mails_to = []
    mails = parse_emails params[:helpers][:mails]
    mails.each do |email|
      new_helper = Helper.new email: email
      new_helper.project = @project
      if new_helper.valid?
        @sent_mails_to << email
        new_helper.save
        HelperMailer.optin_mail(new_helper).deliver_later
      end
    end
    if @sent_mails_to.empty?
      redirect_to project_helpers_subscribe_many_path(@project), flash: {warning: I18n.t("helpers.no_helpers_subscribed")}
    else
      @title = I18n.t "helpers.subscription_successfull"
      render "subscription_successfull"
    end
  end

  def unsubscribe_many
    @title = I18n.t "helpers.unsubscribe_many"
  end

  def unsubscribe_many_post
    mails = parse_emails params[:helpers][:mails]
    mails.each do |email|
      helper = @project.helpers.find_by_email email
      helper.destroy
    end
    redirect_to project_path(@project), flash: {success: I18n.t("helpers.unsubscription_successfull")}
  end

  def unsubscribe
    email = params[:email] || (params[:helper] && params[:helper][:email])
    @helper = Helper.find_by_email email
    unless @helper.nil?
      confirmation_key = params[:confirmation_key]
      if confirmation_key == @helper.confirmation_key
        Rails.logger.info("Unsubscription")
        @helper.delete
        redirect_to root_path, flash:{success: I18n.t("helpers.leave_success")}
      else
        HelperMailer.optout_mail(@helper).deliver_later
        redirect_to root_path, flash:{success: I18n.t("helpers.optout_sent")}
      end
    else
      # Success because otherwise it is possible to determine whether
      # an email is present in our system
      redirect_to root_path, flash:{success: I18n.t("helpers.optout_sent")}
    end
  end
  private
  def get_project
    @project = Project.friendly.find params[:project_id]
  end

  def parse_emails emails
    emails.split(/[\n ,;]/)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_li_link_to t, path, *args
    cls = ""
    if current_page? path
      cls = "active"
    end
    "<li class=\"#{cls}\">#{link_to t, path, *args}</li>".html_safe
  end
end

app/helpers/helpers_helper.rb
module HelpersHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/helpers/create.html.erb
<h1>Helpers#create</h1>
<p>Find me in app/views/helpers/create.html.erb</p>

app/views/helpers/delete.html.erb
<h1>Helpers#delete</h1>
<p>Find me in app/views/helpers/delete.html.erb</p>

app/views/helpers/new.html.erb
<div class="row">
<%= simple_form_for @helper, url: project_helpers_path(@project, invite_key: @project.invite_key),
  html: { class: 'sky-form' } do |f| %>
  <div class="col-md-6">
    <h2><%= I18n.t "project.subscribe", project: @project.name %></h2>
    <%= f.input :email, wrapper: :no_label do %>
      <div class="input-group-addon"><i class="fa fa-envelope"></i></div>
      <%= f.input_field :email, class: 'form-control' %>
    <% end %>
    <button type="submit" class="btn-u pull-right">
      <i class="fa fa-heart"></i> <%= I18n.t "project.subscribe_to", project: @project.name%>
    </button>
  </div>
  <div class="col-md-6">
    <h2><%= I18n.t "project.about", project: @project.name %></h2>
    <p><%= @project.description %></p>
  </div>
<% end %>
</div>

app/views/helpers/subscribe_many.html.erb
<%= simple_form_for(:helpers, url: project_helpers_subscribe_many_post_path(@project)) do |f| %>
  <%= f.input :mails, as: :text, hint: I18n.t("helpers.subscribe_mails")%>
  <%= f.button :submit, class: 'btn-u pull-right', value: I18n.t("helpers.subscribe_many") %>
<% end %>

app/views/helpers/subscription_successfull.html.erb
<ul>
  <% @sent_mails_to.each do |email|%>
    <li><%=email%></li>
  <% end %>
</ul>

app/views/helpers/unsubscribe_many.html.erb
<%= simple_form_for(:helpers, url: project_helpers_unsubscribe_many_post_path(@project)) do |f| %>
  <%= f.input :mails, as: :text, hint: I18n.t("helpers.subscribe_mails")%>
  <%= f.button :submit, class: 'btn-u pull-right', value: I18n.t("helpers.unsubscribe_many") %>
<% end %>