config/routes.rb
Rails.application.routes.draw do

  # Static stuff
  root 'static#index'
  get 'faq' => 'static#faq'
  get 'imprint' => 'static#contactimprint'

  # Controllers
  get 'projects/public'
  resources :projects do
    scope :helpers do
      get 'confirm/:confirmation_key' => 'helpers#confirm', as: :helpers_confirm
      get 'unsubscribe' => 'helpers#unsubscribe', as: :helpers_unsubscribe
      get 'subscribe_many' => 'helpers#subscribe_many', as: :helpers_subscribe_many
      post 'subscribe_many' => 'helpers#subscribe_many_post', as: :helpers_subscribe_many_post
      get 'unsubscribe_many' => 'helpers#unsubscribe_many', as: :helpers_unsubscribe_many
      post 'unsubscribe_many' => 'helpers#unsubscribe_many_post', as: :helpers_unsubscribe_many_post
    end
    resources :helpers
    resources :managers

    resources :requests do
      get 'accept'
      get 'decline'
    end
  end

  if ENV['ENABLE_ADMIN'] == "TRUE"
    # Sidekiq
    require 'sidekiq/web'
    mount Sidekiq::Web => '/admin/sidekiq'
    # Admin
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end

  devise_for :managers, controllers: {
                 confirmations: 'managers/confirmations',
                 sessions: 'managers/sessions'
               }

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
  <head>
    <title><%=
           if @title
             I18n.t "layout.title", title: @title
           else
             I18n.t "layout.pure_title"
             end
           %></title>

    <!-- Meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Favicon -->
    <link rel="shortcut icon" href="favicon.ico">

    <!-- Web Fonts -->
    <% unless ENV['OFFLINE'] %>
      <link rel='stylesheet' type='text/css' href='//fonts.googleapis.com/css?family=Open+Sans:400,300,600&amp;subset=cyrillic,latin'>
    <% end %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>

    <!-- CSS Global Compulsory -->
    <link rel="stylesheet" href="/assets/css/style.css">

    <!-- CSS Header and Footer -->
    <link rel="stylesheet" href="/assets/css/headers/header-default.css">
    <link rel="stylesheet" href="/assets/css/footers/footer-v1.css">

    <!-- CSS Implementing Plugins -->
    <link rel="stylesheet" href="/assets/plugins/animate.css">
    <link rel="stylesheet" href="/assets/plugins/line-icons/line-icons.css">
    <link rel="stylesheet" href="/assets/plugins/font-awesome/css/font-awesome.min.css">
  </head>

  <body>
    <div class="wrapper">
      <!--=== Header ===-->
      <div class="header">
        <div class="container">
          <!-- Logo -->
          <a class="logo" href="/">
            <img src="/assets/img/logo1-default.png" alt="Logo">
          </a>
          <!-- End Logo -->

          <!-- Topbar -->
          <div class="topbar">
            <ul class="loginbar pull-right">
              <% unless current_manager.nil? %>
                <li><%= I18n.t "project.hello_member", email: current_manager.email %></li>
                <li><%= link_to I18n.t("project.logout"), destroy_manager_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to I18n.t("project.login"), new_manager_session_path %></li>
              <% end %>
            </ul>
          </div>
          <!-- End Topbar -->

          <!-- Toggle get grouped for better mobile display -->
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="sr-only"><%= I18n.t "nav.toggle_navigation" %></span>
            <span class="fa fa-bars"></span>
          </button>
          <!-- End Toggle -->
        </div><!--/end container-->

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse mega-menu navbar-responsive-collapse">
          <div class="container">
            <ul class="nav navbar-nav">
              <% unless current_manager.nil? %>
                <%= active_li_link_to I18n.t("nav.manage_project"), project_path(current_manager.project), class: "foo" %>
                <%= active_li_link_to I18n.t("nav.manage_requests"), project_requests_path(current_manager.project) %>
              <% else %>
                <!-- Home -->
                <%= active_li_link_to I18n.t("home.sign_up"), new_project_path %>
                <%= active_li_link_to I18n.t("nav.how_it_works"), "#" %>

              <% end %>
              <%= active_li_link_to I18n.t("nav.public_projects"), projects_public_path %>
              <%= active_li_link_to I18n.t("nav.faq"), faq_path %>
            </ul>
          </div><!--/end container-->
        </div><!--/navbar-collapse-->
      </div>
      <!--=== End Header ===-->
      <!--=== Notification Block ===-->
      <% flash.each do |name, msg| %>
        <div class="alert alert-<%= name%>">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= msg %>
        </div>
      <% end %>
      <!-- End Notofication Block -->

      <% if @nocontainer %>
        <%= yield%>
      <% else %>
        <div class="breadcrumbs">
          <div class="container">
            <h1 class="pull-left"><%= @page_title || @title || "NO TITLE DEFINED"%></h1>
          </div>
        </div>
        <div class="container content">
	      <%= yield %>
        </div>
      <% end %>

      <!--=== Footer Version 1 ===-->
      <div class="footer-v1">
        <div class="footer">
          <div class="container">
            <div class="row">
              <!-- About -->
              <div class="col-md-4 md-margin-bottom-40">
                <a href="/"><img id="logo-footer" class="footer-logo" src="/assets/img/logo2-default.png" alt=""></a>
                <%= t("layout.footer.html")%>
              </div><!--/col-md-4-->
              <!-- End About -->

              <!-- Useful Links -->
              <div class="col-md-4 md-margin-bottom-40">
                <div class="posts">
                  <div class="headline"><h2><%= t "layout.useful_links"%></h2></div>
                  <ul class="list-unstyled link-list">

                    <% unless current_manager.nil? %>
                      <li>
                        <%= link_to I18n.t("project.logout"), destroy_manager_session_path, method: :delete %>
                        <i class="fa fa-angle-right"></i>
                      </li>
                    <% else %>
                      <li>
                        <%= link_to I18n.t("project.login"), new_manager_session_path %>
                        <i class="fa fa-angle-right"></i>
                      </li>
                    <% end %>
                    <li>
                      <%= link_to I18n.t("nav.for_projects"), new_project_path %>
                      <i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                      <%= link_to I18n.t("nav.faq"), faq_path %>
                      <i class="fa fa-angle-right"></i>
                    </li>
                    <li>
                      <%= link_to(I18n.t("nav.imprint"), imprint_path) %>
                      <i class="fa fa-angle-right"></i>
                    </li>
                  </ul>
                </div>
              </div>

              <!-- Latest -->
              <div class="col-md-4 md-margin-bottom-40 map-img">
                <div class="posts">
                  <div class="headline"><h2><%= t "layout.contact_us"%></h2></div>
                  <address class="md-margin-bottom-40">
                            <%= t 'layout.contact_mail' %>: <a href="mailto:<%= ENV['CONTACT_EMAIL'] %>" class=""><%= ENV['CONTACT_EMAIL'] %></a>
                  </address>
                </div>
              </div><!--/col-md-4-->
              <!-- End Latest -->

            </div>
          </div>
        </div><!--/footer-->

        <div class="copyright">
          <div class="container">
            <div class="row">
              <div class="col-md-6">
                <p>
                  <%= # Because why not?
                  date = Time.new
                  if date.year == 2015
                    "2015"
                  else
                    "2015 – #{date.year}"
                  end
                  %> &copy; Helperchain.org | <%= I18n.t "layout.made_with_love" %>
                </p>
              </div>

              <!-- Social Links -->
              <div class="col-md-6">
                <ul class="footer-socials list-inline">
                  <li>
                    <a href="#" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Facebook">
                      <i class="fa fa-facebook"></i>
                    </a>
                  </li>
                  <li>
                    <a href="#" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Google Plus">
                      <i class="fa fa-google-plus"></i>
                    </a>
                  </li>
                  <li>
                    <a href="#" class="tooltips" data-toggle="tooltip" data-placement="top" title="" data-original-title="Twitter">
                      <i class="fa fa-twitter"></i>
                    </a>
                  </li>
                </ul>
              </div>
              <!-- End Social Links -->
            </div>
          </div>
        </div><!--/copyright-->
      </div>
      <!--=== End Footer Version 1 ===-->
    </div><!--/wrapper-->

    <!-- JS Page Level -->
    <script type="text/javascript" src="/assets/js/app.js"></script>
    <!--[if lt IE 9]>
    <script src="/assets/plugins/respond.js"></script>
    <script src="/assets/plugins/html5shiv.js"></script>
    <script src="/assets/plugins/placeholder-IE-fixes.js"></script>
    <![endif]-->
    <script>
     (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
       (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                              m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
     })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

     ga('create', 'UA-69252369-1', 'auto');
     ga('send', 'pageview');

    </script>
  </body>
</html>

app/views/layouts/helper_mailer.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <p><%= I18n.t "mail.greeting" %></p>
    <%= yield %>

    <p>
      <%= I18n.t "mail.farewell" %><br />
      <%= I18n.t "mail.farewell_team" %>
    </p>

    <% unless @helper.nil? %>
    <p>
      <%= I18n.t "mail.unsubscribe_text"%><br />
      <%= link_to I18n.t("mail.optout_link"), project_helpers_unsubscribe_url(project_id: @helper.project, email: @helper.email, confirmation_key: @helper.confirmation_key) %>
    </p>
    <% end %>
  </body>
</html>

app/views/layouts/helper_mailer.text.erb
<%= I18n.t "mail.greeting" %>

<%= yield %>

<%= I18n.t "mail.farewell" %>
<%= I18n.t "mail.farewell_team" %>


<% unless @helper.nil? %>
---
<%= I18n.t "helpers.unsubscribe_text"%>
<%= project_helpers_unsubscribe_url(project_id: @helper.project, email: @helper.email, confirmation_key: @helper.confirmation_key) %>
<% end %>